---
- name: "Verify EnMasse deployment succeeded"
  block:
    - name: Ensure address space controller pod is ready
      shell: oc get pods --selector='name=address-space-controller' -o jsonpath='{.items[*].status.containerStatuses[0].ready}' -n {{ enmasse_namespace }}
      register: result
      until: "'true' in result.stdout"
      retries: 50
      delay: 10
      changed_when: False
    - name: Ensure api server pod is ready
      shell: oc get pods --selector='component=api-server' -o jsonpath='{.items[*].status.containerStatuses[0].ready}' -n {{ enmasse_namespace }}
      register: result
      until: "'true' in result.stdout"
      retries: 50
      delay: 10
      changed_when: False
    - name: Ensure server broker pod is ready
      shell: oc get pods --selector='component=service-broker' -o jsonpath='{.items[*].status.containerStatuses[0].ready}' -n {{ enmasse_namespace }}
      register: result
      until: "'true' in result.stdout"
      retries: 50
      delay: 10
      changed_when: False
