---
- name: Create {{ mobile_security_service_namespace }} namespace
  include_role:
    name: namespace
  vars:
    namespace: "{{ mobile_security_service_namespace }}"
    display_name: "{{ mobile_security_service_display_name }}"

- name: Add labels to namespace
  shell: oc patch ns {{ mobile_security_service_namespace }} --patch '{"metadata":{"labels":{"{{ monitoring_label_name }}":"{{ monitoring_label_value }}", "integreatly-middleware-service":"true"}}}'
  register: namespace_patch
  failed_when: namespace_patch.stderr != '' and 'not patched' not in namespace_patch.stderr
  changed_when: namespace_patch.rc == 0

- name: Create Mobile Security Service Operator Resources
  shell: "oc create -f {{ item }} -n {{ mobile_security_service_namespace }}"
  with_items: "{{ mobile_security_service_operator_resource_items }}"
  register: mobile_security_service_operator_resource_cmd
  failed_when: mobile_security_service_operator_resource_cmd.stderr != '' and 'AlreadyExists' not in mobile_security_service_operator_resource_cmd.stderr

- name: Generate Mobile Security Service DB custom resource template
  template:
    src: "mobile-security-service-db-cr2.yml.j2"
    dest: /tmp/mobile-security-service-db-cr2.yml

- name: Create Mobile Security Service DB custom resource
  shell: oc create -f /tmp/mobile-security-service-db-cr2.yml -n {{ mobile_security_service_namespace }}
  register: create_mobile_security_service_db_custom_resource_cmd
  failed_when: create_mobile_security_service_db_custom_resource_cmd.stderr != '' and 'AlreadyExists' not in create_mobile_security_service_db_custom_resource_cmd.stderr
  changed_when: create_mobile_security_service_db_custom_resource_cmd.rc == 0

# - name: "Wait for Mobile Security Service DB pods to be ready"
#   shell: "oc get pods --namespace={{ mobile_security_service_namespace }} --selector='deployment={{ mobile_security_service_name }}-db' -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w"
#   register: mobile_security_service_db_result
#   until: mobile_security_service_db_result.stdout.find("1") != -1
#   retries: 90
#   delay: 5

- name: Generate Mobile Security Service custom resource template
  template:
    src: "mobile-security-service-cr2.yml.j2"
    dest: /tmp/mobile-security-service-cr2.yml

- name: Create Mobile Security Service custom resource
  shell: oc create -f /tmp/mobile-security-service-cr2.yml -n {{ mobile_security_service_namespace }}
  register: create_mobile_security_service_custom_resource_cmd
  failed_when: create_mobile_security_service_custom_resource_cmd.stderr != '' and 'AlreadyExists' not in create_mobile_security_service_custom_resource_cmd.stderr
  changed_when: create_mobile_security_service_custom_resource_cmd.rc == 0

# - name: "Wait for Mobile Security Service pods to be ready"
#   shell: "oc get pods --namespace={{ mobile_security_service_namespace }} --selector='deployment={{ mobile_security_service_name }}' -o jsonpath='{.items[*].status.containerStatuses[?(@.ready==true)].ready}' | wc -w"
#   register: mobile_security_service_result
#   until: mobile_security_service_result.stdout.find("1") != -1
#   retries: 90
#   delay: 5

# - name: Get the name of the Mobile Security Service pod
#   shell: "oc get pods --namespace={{ mobile_security_service_namespace }} --selector='deployment={{ mobile_security_service_namespace }}' -o jsonpath='{.items[0].metadata.name}'"
#   register: mobile_security_service_pod_name